baseURL = 'https://notesfinity.com/'
languageCode = 'en-us'
title = 'Notesfinity'
theme = 'notesfinity'

uglyURLs = false
[permalinks]
posts = "/:slug/"

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
[params]
  math = true