baseURL = 'https://notesfinity.com/'
languageCode = 'en-us'
title = 'Notesfinity'
theme = 'notesfinity'
uglyURLs = false
canonifyURLs = false  # Disable canonical URLs with .html extension
[permalinks]
posts = "/:slug/"

[markup.goldmark.renderer]
unsafe = true