baseURL = 'https://romanthapa8848.github.io/notesfinity-hugo/'
languageCode = 'en-us'
title = 'Notesfinity'
theme = 'notesfinity'

[params]
  githubURL = "https://romanthapa8848.github.io/notesfinity-hugo/"
