baseURL = 'https://gyanpedia.com'
languageCode = 'en-us'
title = 'Gyanpedia'
theme = 'gyanpedia'

uglyURLs = false

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
[params]
  math = true

  